# Generated by Django 2.0.3 on 2018-03-29 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_produto_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='clienteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.Cliente'),
        ),
    ]
