# Generated by Django 2.0.3 on 2018-03-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_maisvendidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaisVendidos',
        ),
    ]
