# Generated by Django 2.0.3 on 2018-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0007_maisvendidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maisvendidos',
            old_name='produto',
            new_name='descricao',
        ),
    ]
