# Generated by Django 2.0.3 on 2018-03-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0009_melhoresdomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendasMensais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=4)),
                ('mes', models.CharField(max_length=2)),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
    ]
