# Generated by Django 2.0.3 on 2018-03-29 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0010_vendasmensais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendasmensais',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='vendasmensais',
            name='valor',
        ),
        migrations.AddField(
            model_name='vendasmensais',
            name='meses',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
