# Generated by Django 2.0.3 on 2018-03-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20180328_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='teste.Produto'),
        ),
    ]
