# Generated by Django 2.0.3 on 2018-03-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0011_auto_20180329_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaisVendidos',
        ),
        migrations.DeleteModel(
            name='MelhoresDoMes',
        ),
        migrations.DeleteModel(
            name='VendasMensais',
        ),
    ]
