# Generated by Django 2.0.3 on 2018-03-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0012_auto_20180329_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisVendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('qtd', models.IntegerField()),
            ],
        ),
    ]
