# Generated by Django 2.0.3 on 2018-03-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0015_vendasmensais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendasmensais',
            name='meses',
            field=models.CharField(max_length=500),
        ),
    ]
