# Generated by Django 2.0.3 on 2018-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0016_auto_20180330_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendasmensais',
            name='meses',
            field=models.CharField(max_length=300),
        ),
    ]
