# Generated by Django 2.0.3 on 2018-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0018_auto_20180330_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melhoresdomes',
            name='vendasMes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendasmensais',
            name='meses',
            field=models.CharField(max_length=200),
        ),
    ]
